#!/bin/bash

DIR=/home/maunza/maunza/last
for i in `seq 0 9`; do 
    echo "**********"
    echo "BLOOD $i: `date`"
    echo "**********"
    $DIR/last-utils/wrapper10 $DIR/fminer/folds.lastpm/bloodbarr.f22.$i.train.svd15.graphml $DIR/ofsdata/folds/bloodbarr.$i.train.smi

    echo "**********"
    echo "NCTRER $i: `date`"
    echo "**********"
    $DIR/last-utils/wrapper10 $DIR/fminer/folds.lastpm/nctrer.f14.$i.train.svd15.graphml $DIR/ofsdata/folds/nctrer.$i.train.smi

    echo "**********"
    echo "YOSHIDA $i: `date`"
    echo "**********"
    $DIR/last-utils/wrapper10 $DIR/fminer/folds.lastpm/yoshida.f14.$i.train.svd15.graphml $DIR/ofsdata/folds/yoshida.$i.train.smi
done
